### ISSUE TITLE
bad example code

### ISSUE THREAD

**Issue by Morriz** [wercker/workflows-kubernetes-demo#2]
This is based on a very old release of kubernetes (using 'rolling-update'). The preferred solution is to use 'deployments'. You can find an example in my repo here: [k8sdemo-api](https://github.com/Morriz/k8sdemo-api).
It uses my own custom deployment step, which could be made into an official wercker one. It works around the absence of liveness probes in kubernetes configs, making it a robust solution for deployments.

**Comment by mies** [comment]
hi @Morriz we've updated the `wercker.yml` and now leverage *deployments*. Thanks for the feedback and sorry this took a while!

cheers!
