### ISSUE TITLE
Failing code at push-release

### ISSUE THREAD

**Issue by otaviosoares** [wercker/workflows-kubernetes-demo#8]
I had a problem with this [line](https://github.com/wercker/workflows-kubernetes-demo/blob/master/wercker.yml#L81).

```
mv $WERCKER_SOURCE_DIR/* /usr/share/nginx/html
```

As it moves the entire content of the source dir, the next pipeline fails at getting the code.

I've changed to 

```
cp -RL $WERCKER_SOURCE_DIR/* /usr/share/nginx/html
```

**Comment by hatchan** [comment]
The step before that one (https://github.com/wercker/workflows-kubernetes-demo/blob/master/wercker.yml#L73-L75) we grab the `deployments` directory and move it to `$WERCKER_OUTPUT_DIR`. This causes wercker to ignore the wercker source directory, and use the `$WERCKER_OUTPUT_DIR` for the next pipeline. 

Also the next line completely removes all content from the the `$WERCKER_SOURCE_DIR`. 

So not sure what is going wrong.

**Comment by otaviosoares** [comment]
Thank you for the reply. I was running an older version which doesn't have the mv deployments part.
